In [2]:
import numpy as np

In [16]:
#1. Create a null vector of size 10 but the fifth value which is 1.
null_vector=np.zeros(10)
null_vector[5]=1
null_vector

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [22]:
#2. Create a vector with values ranging from 10 to 49.
vector=np.arange(10,49)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [28]:
#3. Create a 3x3 matrix with values ranging from 0 to 8
matrix=np.arange(0,9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
# 4. Find indices of non-zero elements from [1,2,0,0,4,0]
vector1=np.array([1,2,0,0,4,0])
non_zero=[index for index,element in enumerate(vector1) if element!=0]
print(non_zero)

[0, 1, 4]


In [27]:
# Create a 10x10 array with random values and find the minimum and maximum values.
ar=np.random.randint(1,101,100).reshape(10,10)
print(ar)
print('-'*50)
print(ar.min())
print('-'*50)
print(ar.max())

[[78 74 68 13 67 34 43 23  6 65]
 [55 79 52 50 29 24  3 91 15  8]
 [44 18 50 58 67 53 60 99 62 94]
 [82 15 73 99 69  5 90 66 78 51]
 [87 47 35 21 34  9 47 22 48 28]
 [71 49  7 63 63  3 83 10 62 25]
 [34 87 64 58 89 90 58 14 29 92]
 [49 25 50 60 42 54  3 35 26 66]
 [72 35 45 13 14 97  3 25 98 11]
 [86 93 17 71 69 11 20 60 76 66]]
--------------------------------------------------
3
--------------------------------------------------
99


In [30]:
# 6. Create a random vector of size 30 and find the mean value.
vector2=np.arange(0,31)
print(vector2)
print('-'*50)
vector2.mean()

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]
--------------------------------------------------


15.0